"""
Django settings for A project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta
from urllib.parse import urlparse
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p1c_cc7!z41v=2c98+aliz$x26nh_8my8-of^i6prx6_lvto%l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'accounts.apps.AccountsConfig',
    'home.apps.HomeConfig',
    'products.apps.ProductsConfig',
    'products_api.apps.ProductsApiConfig',
    'order.apps.OrderConfig',

    # thireid party apps
    'rest_framework',
    'mptt',
    'django_json_widget',
    'constance',
    'constance.backends.database',
    'rest_framework_simplejwt',
    'cloudinary',
    'cloudinary_storage',

]

# تنظیمات Constance
CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'

# تعریف تنظیمات قابل تغییر
CONSTANCE_CONFIG = {
    'ONLINE_PAYMENT_ENABLED': (True, 'فعال/غیرفعال بودن پرداخت آنلاین'),
    'MINIMUM_ORDER_AMOUNT': (10000, 'حداقل مبلغ سفارش (تومان)'),
    'FREE_SHIPPING_THRESHOLD': (100000, 'حداقل مبلغ برای ارسال رایگان'),
    'SHOP_PHONE': ('', 'شماره تلفن فروشگاه'),
    'SHOP_EMAIL': ('', 'ایمیل فروشگاه'),
    'MAINTENANCE_MODE': (False, 'حالت تعمیر و نگهداری'),
    'PAYMENT_CARD_NUMBER': ('6037-9975-9999-9999', 'شماره کارت برای پرداخت'),
    'PAYMENT_CARD_OWNER': ('فروشگاه دیجیتال', 'نام صاحب کارت'),
    'PAYMENT_BANK_NAME': ('بانک ملی', 'نام بانک'),
}

# گروه‌بندی تنظیمات در پنل ادمین
CONSTANCE_CONFIG_FIELDSETS = {
    'عمومی': ('MAINTENANCE_MODE', 'SHOP_PHONE', 'SHOP_EMAIL'),
    'پرداخت': ('ONLINE_PAYMENT_ENABLED', 'MINIMUM_ORDER_AMOUNT'),
    'اطلاعات کارت بانکی': (
        'PAYMENT_CARD_NUMBER',
        'PAYMENT_CARD_OWNER',
        'PAYMENT_BANK_NAME',
    ),
    'ارسال': ('FREE_SHIPPING_THRESHOLD',),
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'A.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'order.context_processors.cart_context',
            ],
        },
    },
]

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

STORAGES = {
    # ...
    'default':{
        'BACKEND': 'cloudinary_storage.storage.MediaCloudinaryStorage',
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}






WSGI_APPLICATION = 'A.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases



load_dotenv()
tmpPostgres = urlparse(os.getenv("DATABASE_URL"))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': tmpPostgres.path.replace('/', ''),
        'USER': tmpPostgres.username,
        'PASSWORD': tmpPostgres.password,
        'HOST': tmpPostgres.hostname,
        'PORT': 5432,
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'DivineBeauty',  # نام دیتابیس
#         'USER': 'postgres',      # نام کاربری دیتابیس
#         'PASSWORD': 'postgres',  # پسورد دیتابیس
#         'HOST': 'localhost',   # آدرس هاست (برای استفاده از دیتابیس لوکال localhost رو بذار)
#         'PORT': '5432',        # پورت پیش‌فرض PostgreSQL
#     }
# }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom user model
AUTH_USER_MODEL = 'accounts.CustomUser'
LOGIN_REDIRECT_URL = 'home:home'

load_dotenv()
# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # آدرس جیمیل خودت
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # رمز عبور اپ (توضیحش پایین هست)


CELERY_BROKER_URL = 'redis://localhost:6379'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
}


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}



CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}



MEDIA_URL = 'media/'



