# Generated by Django 5.2 on 2025-04-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otpcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpCode',
        ),
    ]
