# Generated by Django 5.2 on 2025-05-03 08:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_cartitem_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_name',
            field=models.CharField(default='بدون نام', max_length=255, verbose_name='نام تحویل\u200cگیرنده'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiver_phone_number',
            field=models.CharField(default='بدون شماره تلفن', max_length=15, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'شماره تلفن باید ۱۱ رقم باشد')]),
        ),
    ]
