# Generated by Django 5.2 on 2025-05-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_order_tracking_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'درحال پردازش'), ('confirmed', 'تایید شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='type_of_payment',
            field=models.CharField(choices=[('online', 'پرداخت آنلاین'), ('card', 'پرداخت با کارت')], default='online', max_length=20),
        ),
    ]
