# Generated by Django 5.2 on 2025-05-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_order_status_order_type_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'در انتظار پرداخت'), ('pending', 'درحال پردازش'), ('confirmed', 'تایید شده'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='waiting_for_payment', max_length=20),
        ),
    ]
