# Generated by Django 5.2 on 2025-05-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type_of_payment',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('waiting_for_payment', 'در انتظار پرداخت'), ('processing', 'در حال پردازش'), ('shipped', 'ارسال شده'), ('delivered', 'تحویل داده شده'), ('undelivered', 'تحویل داده نشد'), ('cancelled', 'لغو شده')], default='waiting_for_payment', max_length=20),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ پرداختی (تومان)')),
                ('payment_method', models.CharField(choices=[('online', 'پرداخت آنلاین'), ('card', 'پرداخت با کارت')], max_length=20, verbose_name='روش پرداخت')),
                ('ref_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره مرجع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('canceled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت پرداخت')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پرداخت')),
                ('receipt', models.ImageField(blank=True, null=True, upload_to='payments/receipts/', verbose_name='رسید پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='order.order', verbose_name='سفارش')),
            ],
        ),
    ]
