# Generated by Django 5.2 on 2025-04-15 21:27

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام برند')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام برچسب')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته\u200cبندی')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='دسته\u200cبندی والد')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('slug', models.SlugField(unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='توضیحات محصول')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='products/main/', verbose_name='تصویر اصلی')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('skintype', models.CharField(blank=True, choices=[('normal', 'نرمال'), ('oily', 'چرب'), ('dry', 'خشک'), ('combination', 'مختلط'), ('sensitive', 'حساس')], max_length=20, null=True, verbose_name='نوع پوست')),
                ('discount_price', models.IntegerField(blank=True, null=True, verbose_name='قیمت تخفیف\u200cخورده')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='موجودی انبار')),
                ('is_available', models.BooleanField(default=True, verbose_name='موجود')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('usage_instructions', models.TextField(blank=True, null=True, verbose_name='دستورالعمل مصرف')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand', verbose_name='برند')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category', verbose_name='دسته\u200cبندی')),
                ('lable', models.ManyToManyField(blank=True, to='products.productlabel', verbose_name='برچسب')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product', verbose_name='محصول')),
            ],
        ),
    ]
