# Generated by Django 5.2 on 2025-04-20 14:54

import utility
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_brand_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=utility.AutoSlugField(blank=True, null=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='productlabel',
            name='slug',
            field=utility.AutoSlugField(blank=True, null=True, unique=True, verbose_name='نامک'),
        ),
    ]
