# Generated by Django 5.2 on 2025-04-20 17:02

import utility
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_slug_alter_productlabel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=utility.AutoSlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=utility.AutoSlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='productlabel',
            name='slug',
            field=utility.AutoSlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='نامک'),
        ),
    ]
