# Generated by Django 5.2 on 2025-04-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_lable_product_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, null=True, verbose_name='ویژگی\u200cها'),
        ),
    ]
